wandb_version: 1

activation_hidden:
  value: relu
batch_size:
  value: 128
hidden_width:
  value: 256
l2_coeff:
  value: 0
learning_rate:
  value: 0.0003
num_hidden_layers:
  value: 3
optimizer:
  value: adam
weights_init:
  value: HeNor
